version: '3'
name: environment
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /data:/data
    networks:
      - environment

  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - environment

  traefik:
    container_name: traefik
    image: traefik:v2.9
    restart: always
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./private/traefik.yml:/traefik.yml
      - $HOME/letsencrypt:/letsencrypt
    networks:
      - environment

networks:
  environment:
    driver: bridge
    name: environment