version: '3'
name: php_example
services:
  app:
    container_name: php_example_app
    image: php-apache-custom
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./app:/var/www/app
    networks:
      - php_example

networks:
  php_example:
    driver: bridge
    name: php_example