version: '3'
name: env_example
services:
  app:
    container_name: env_example_container
    image: nginx:stable-alpine
    networks:
      - environment
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.env_example.rule=Host(`env_example.local`)"
      - "traefik.http.services.env_example.loadbalancer.server.port=80"

networks:
  environment:
    name: environment
    external: true